
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "F:/Program Files/Cmake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "F:/Program Files/Cmake/share/cmake-4.2/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "F:/vs/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/"
      - "F:/vs/Common7/IDE/VC/vcpackages/"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TestWindow/"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/"
      - "F:/vs/MSBuild/Current/Bin/Roslyn/"
      - "C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64/"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/"
      - "F:/vs/Team Tools/DiagnosticsHub/Collector/"
      - "F:/vs/Common7/IDE/Extensions/Microsoft/CodeCoverage.Console/"
      - "E:/Windows Kits/10/bin/10.0.26100.0/x64/"
      - "E:/Windows Kits/10/bin/x64/"
      - "F:/vs/MSBuild/Current/Bin/amd64/"
      - "C:/Windows/Microsoft.NET/Framework64/v4.0.30319/"
      - "F:/vs/Common7/IDE/"
      - "F:/vs/Common7/Tools/"
      - "F:/Program Files (x86)/cursor/resources/app/resources/helpers/"
      - "F:/mingw/mingw64/bin/"
      - "F:/wy/depot_tools/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/"
      - "C:/Program Files (x86)/VMware/VMware Workstation/bin/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "E:/program/vs_program/Common7/IDE/"
      - "F:/Qt/6.8.3/mingw_64/bin/"
      - "F:/Qt/6.8.3/msvc2022_64/bin/"
      - "C:/Program Files/dotnet/"
      - "F:/wy/ffmpeg-master-latest-win64-gpl-shared/bin/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "E:/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Program Files/MySQL/MySQL Server 8.0/bin/"
      - "F:/Program Files/Cmake/bin/"
      - "C:/Program Files/Java/jdk-25.0.2/bin/"
      - "F:/wy/SDL3/bin/"
      - "F:/Qt/Tools/mingw1310_64/"
      - "C:/Program Files/MySQL/MySQL Server 8.0/lib/"
      - "F:/opencv/build/x64/vc16/bin/"
      - "F:/ninja/"
      - "F:/doxygen/bin/"
      - "F:/nodejs/"
      - "F:/wy/vcpkg/"
      - "F:/python3/Scripts/"
      - "F:/python3/"
      - "F:/Program Files (x86)/Trae CN/bin/"
      - "C:/Program Files/MySQL/MySQL Shell 8.0/bin/"
      - "C:/Users/30840/AppData/Local/Microsoft/WindowsApps/"
      - "E:/Users/30840/AppData/Local/Programs/Microsoft VS Code Insiders/bin/"
      - "F:/Program Files/Microsoft VS Code/bin/"
      - "C:/Users/30840/.dotnet/tools/"
      - "F:/Program Files/IntelliJ IDEA 2025.3.3/bin/"
      - "F:/Program Files (x86)/cursor/resources/app/bin/"
      - "F:/Program Files (x86)/DataGrip 2025.3.5/bin/"
      - "C:/Users/30840/AppData/Roaming/npm/"
      - "C:/Users/30840/AppData/Local/Programs/DockerDesktop/resources/bin/"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/"
      - "F:/vs/Common7/IDE/VC/Linux/bin/ConnectionManagerExe/"
      - "F:/vs/VC/vcpkg/"
    searched_directories:
      - "F:/vs/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/ninja-build.com"
      - "F:/vs/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/ninja-build.exe"
      - "F:/vs/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/ninja-build"
      - "F:/vs/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/ninja.com"
      - "F:/vs/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/ninja.exe"
      - "F:/vs/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/ninja"
      - "F:/vs/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/samu.com"
      - "F:/vs/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/samu.exe"
      - "F:/vs/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/samu"
      - "F:/vs/Common7/IDE/VC/vcpackages/ninja-build.com"
      - "F:/vs/Common7/IDE/VC/vcpackages/ninja-build.exe"
      - "F:/vs/Common7/IDE/VC/vcpackages/ninja-build"
      - "F:/vs/Common7/IDE/VC/vcpackages/ninja.com"
      - "F:/vs/Common7/IDE/VC/vcpackages/ninja.exe"
      - "F:/vs/Common7/IDE/VC/vcpackages/ninja"
      - "F:/vs/Common7/IDE/VC/vcpackages/samu.com"
      - "F:/vs/Common7/IDE/VC/vcpackages/samu.exe"
      - "F:/vs/Common7/IDE/VC/vcpackages/samu"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TestWindow/ninja-build.com"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TestWindow/ninja-build.exe"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TestWindow/ninja-build"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TestWindow/ninja.com"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TestWindow/ninja.exe"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TestWindow/ninja"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TestWindow/samu.com"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TestWindow/samu.exe"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TestWindow/samu"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/ninja-build.com"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/ninja-build.exe"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/ninja-build"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/ninja.com"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/ninja.exe"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/ninja"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/samu.com"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/samu.exe"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/samu"
      - "F:/vs/MSBuild/Current/Bin/Roslyn/ninja-build.com"
      - "F:/vs/MSBuild/Current/Bin/Roslyn/ninja-build.exe"
      - "F:/vs/MSBuild/Current/Bin/Roslyn/ninja-build"
      - "F:/vs/MSBuild/Current/Bin/Roslyn/ninja.com"
      - "F:/vs/MSBuild/Current/Bin/Roslyn/ninja.exe"
      - "F:/vs/MSBuild/Current/Bin/Roslyn/ninja"
      - "F:/vs/MSBuild/Current/Bin/Roslyn/samu.com"
      - "F:/vs/MSBuild/Current/Bin/Roslyn/samu.exe"
      - "F:/vs/MSBuild/Current/Bin/Roslyn/samu"
      - "C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64/ninja-build.com"
      - "C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64/ninja-build.exe"
      - "C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64/ninja-build"
      - "C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64/ninja.com"
      - "C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64/ninja.exe"
      - "C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64/ninja"
      - "C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64/samu.com"
      - "C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64/samu.exe"
      - "C:/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.8 Tools/x64/samu"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/ninja-build.com"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/ninja-build.exe"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/ninja-build"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/ninja.com"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/ninja.exe"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/ninja"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/samu.com"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/samu.exe"
      - "F:/vs/Common7/IDE/CommonExtensions/Microsoft/FSharp/Tools/samu"
      - "F:/vs/Team Tools/DiagnosticsHub/Collector/ninja-build.com"
      - "F:/vs/Team Tools/DiagnosticsHub/Collector/ninja-build.exe"
      - "F:/vs/Team Tools/DiagnosticsHub/Collector/ninja-build"
      - "F:/vs/Team Tools/DiagnosticsHub/Collector/ninja.com"
      - "F:/vs/Team Tools/DiagnosticsHub/Collector/ninja.exe"
      - "F:/vs/Team Tools/DiagnosticsHub/Collector/ninja"
      - "F:/vs/Team Tools/DiagnosticsHub/Collector/samu.com"
      - "F:/vs/Team Tools/DiagnosticsHub/Collector/samu.exe"
      - "F:/vs/Team Tools/DiagnosticsHub/Collector/samu"
      - "F:/vs/Common7/IDE/Extensions/Microsoft/CodeCoverage.Console/ninja-build.com"
      - "F:/vs/Common7/IDE/Extensions/Microsoft/CodeCoverage.Console/ninja-build.exe"
      - "F:/vs/Common7/IDE/Extensions/Microsoft/CodeCoverage.Console/ninja-build"
      - "F:/vs/Common7/IDE/Extensions/Microsoft/CodeCoverage.Console/ninja.com"
      - "F:/vs/Common7/IDE/Extensions/Microsoft/CodeCoverage.Console/ninja.exe"
      - "F:/vs/Common7/IDE/Extensions/Microsoft/CodeCoverage.Console/ninja"
      - "F:/vs/Common7/IDE/Extensions/Microsoft/CodeCoverage.Console/samu.com"
      - "F:/vs/Common7/IDE/Extensions/Microsoft/CodeCoverage.Console/samu.exe"
      - "F:/vs/Common7/IDE/Extensions/Microsoft/CodeCoverage.Console/samu"
      - "E:/Windows Kits/10/bin/10.0.26100.0/x64/ninja-build.com"
      - "E:/Windows Kits/10/bin/10.0.26100.0/x64/ninja-build.exe"
      - "E:/Windows Kits/10/bin/10.0.26100.0/x64/ninja-build"
      - "E:/Windows Kits/10/bin/10.0.26100.0/x64/ninja.com"
      - "E:/Windows Kits/10/bin/10.0.26100.0/x64/ninja.exe"
      - "E:/Windows Kits/10/bin/10.0.26100.0/x64/ninja"
      - "E:/Windows Kits/10/bin/10.0.26100.0/x64/samu.com"
      - "E:/Windows Kits/10/bin/10.0.26100.0/x64/samu.exe"
      - "E:/Windows Kits/10/bin/10.0.26100.0/x64/samu"
      - "E:/Windows Kits/10/bin/x64/ninja-build.com"
      - "E:/Windows Kits/10/bin/x64/ninja-build.exe"
      - "E:/Windows Kits/10/bin/x64/ninja-build"
      - "E:/Windows Kits/10/bin/x64/ninja.com"
      - "E:/Windows Kits/10/bin/x64/ninja.exe"
      - "E:/Windows Kits/10/bin/x64/ninja"
      - "E:/Windows Kits/10/bin/x64/samu.com"
      - "E:/Windows Kits/10/bin/x64/samu.exe"
      - "E:/Windows Kits/10/bin/x64/samu"
      - "F:/vs/MSBuild/Current/Bin/amd64/ninja-build.com"
      - "F:/vs/MSBuild/Current/Bin/amd64/ninja-build.exe"
      - "F:/vs/MSBuild/Current/Bin/amd64/ninja-build"
      - "F:/vs/MSBuild/Current/Bin/amd64/ninja.com"
      - "F:/vs/MSBuild/Current/Bin/amd64/ninja.exe"
      - "F:/vs/MSBuild/Current/Bin/amd64/ninja"
      - "F:/vs/MSBuild/Current/Bin/amd64/samu.com"
      - "F:/vs/MSBuild/Current/Bin/amd64/samu.exe"
      - "F:/vs/MSBuild/Current/Bin/amd64/samu"
      - "C:/Windows/Microsoft.NET/Framework64/v4.0.30319/ninja-build.com"
      - "C:/Windows/Microsoft.NET/Framework64/v4.0.30319/ninja-build.exe"
      - "C:/Windows/Microsoft.NET/Framework64/v4.0.30319/ninja-build"
      - "C:/Windows/Microsoft.NET/Framework64/v4.0.30319/ninja.com"
      - "C:/Windows/Microsoft.NET/Framework64/v4.0.30319/ninja.exe"
      - "C:/Windows/Microsoft.NET/Framework64/v4.0.30319/ninja"
      - "C:/Windows/Microsoft.NET/Framework64/v4.0.30319/samu.com"
      - "C:/Windows/Microsoft.NET/Framework64/v4.0.30319/samu.exe"
      - "C:/Windows/Microsoft.NET/Framework64/v4.0.30319/samu"
      - "F:/vs/Common7/IDE/ninja-build.com"
      - "F:/vs/Common7/IDE/ninja-build.exe"
      - "F:/vs/Common7/IDE/ninja-build"
      - "F:/vs/Common7/IDE/ninja.com"
      - "F:/vs/Common7/IDE/ninja.exe"
      - "F:/vs/Common7/IDE/ninja"
      - "F:/vs/Common7/IDE/samu.com"
      - "F:/vs/Common7/IDE/samu.exe"
      - "F:/vs/Common7/IDE/samu"
      - "F:/vs/Common7/Tools/ninja-build.com"
      - "F:/vs/Common7/Tools/ninja-build.exe"
      - "F:/vs/Common7/Tools/ninja-build"
      - "F:/vs/Common7/Tools/ninja.com"
      - "F:/vs/Common7/Tools/ninja.exe"
      - "F:/vs/Common7/Tools/ninja"
      - "F:/vs/Common7/Tools/samu.com"
      - "F:/vs/Common7/Tools/samu.exe"
      - "F:/vs/Common7/Tools/samu"
      - "F:/Program Files (x86)/cursor/resources/app/resources/helpers/ninja-build.com"
      - "F:/Program Files (x86)/cursor/resources/app/resources/helpers/ninja-build.exe"
      - "F:/Program Files (x86)/cursor/resources/app/resources/helpers/ninja-build"
      - "F:/Program Files (x86)/cursor/resources/app/resources/helpers/ninja.com"
      - "F:/Program Files (x86)/cursor/resources/app/resources/helpers/ninja.exe"
      - "F:/Program Files (x86)/cursor/resources/app/resources/helpers/ninja"
      - "F:/Program Files (x86)/cursor/resources/app/resources/helpers/samu.com"
      - "F:/Program Files (x86)/cursor/resources/app/resources/helpers/samu.exe"
      - "F:/Program Files (x86)/cursor/resources/app/resources/helpers/samu"
      - "F:/mingw/mingw64/bin/ninja-build.com"
      - "F:/mingw/mingw64/bin/ninja-build.exe"
      - "F:/mingw/mingw64/bin/ninja-build"
      - "F:/mingw/mingw64/bin/ninja.com"
      - "F:/mingw/mingw64/bin/ninja.exe"
      - "F:/mingw/mingw64/bin/ninja"
      - "F:/mingw/mingw64/bin/samu.com"
      - "F:/mingw/mingw64/bin/samu.exe"
      - "F:/mingw/mingw64/bin/samu"
      - "F:/wy/depot_tools/ninja-build.com"
      - "F:/wy/depot_tools/ninja-build.exe"
      - "F:/wy/depot_tools/ninja-build"
      - "F:/wy/depot_tools/ninja.com"
      - "F:/wy/depot_tools/ninja.exe"
    found: "F:/wy/depot_tools/ninja"
    search_context:
      ENV{PATH}:
        - "F:\\vs\\VC\\Tools\\MSVC\\14.51.36231\\bin\\HostX64\\x64"
        - "F:\\vs\\Common7\\IDE\\VC\\VCPackages"
        - "F:\\vs\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow"
        - "F:\\vs\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer"
        - "F:\\vs\\MSBuild\\Current\\bin\\Roslyn"
        - "C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v10.0A\\bin\\NETFX 4.8 Tools\\x64\\"
        - "F:\\vs\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\Tools"
        - "F:\\vs\\Team Tools\\DiagnosticsHub\\Collector"
        - "F:\\vs\\Common7\\IDE\\Extensions\\Microsoft\\CodeCoverage.Console"
        - "E:\\Windows Kits\\10\\bin\\10.0.26100.0\\\\x64"
        - "E:\\Windows Kits\\10\\bin\\\\x64"
        - "F:\\vs\\\\MSBuild\\Current\\Bin\\amd64"
        - "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319"
        - "F:\\vs\\Common7\\IDE\\"
        - "F:\\vs\\Common7\\Tools\\"
        - "f:\\Program Files (x86)\\cursor\\resources\\app\\resources\\helpers"
        - "F:\\mingw\\mingw64\\bin"
        - "F:\\wy\\depot_tools"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\Program Files (x86)\\VMware\\VMware Workstation\\bin\\"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "E:\\program\\vs_program\\Common7\\IDE"
        - "F:\\Qt\\6.8.3\\mingw_64\\bin"
        - "F:\\Qt\\6.8.3\\msvc2022_64\\bin"
        - "C:\\Program Files\\dotnet\\"
        - "F:\\wy\\ffmpeg-master-latest-win64-gpl-shared\\bin"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "E:\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin"
        - "F:\\Program Files\\Cmake\\bin"
        - "C:\\Program Files\\Java\\jdk-25.0.2\\bin"
        - "F:\\wy\\SDL3\\bin"
        - "F:\\Qt\\Tools\\mingw1310_64"
        - "C:\\Program Files\\MySQL\\MySQL Server 8.0\\lib"
        - "F:\\Qt\\6.8.3\\mingw_64\\bin"
        - "F:\\opencv\\build\\x64\\vc16\\bin"
        - "F:\\ninja"
        - "F:\\doxygen\\bin"
        - "F:\\nodejs\\"
        - "F:\\wy\\vcpkg"
        - "F:\\wy\\depot_tools"
        - "F:\\python3\\Scripts\\"
        - "F:\\python3\\"
        - "f:\\Program Files (x86)\\Trae CN\\bin"
        - "C:\\Program Files\\MySQL\\MySQL Shell 8.0\\bin\\"
        - "C:\\Users\\30840\\AppData\\Local\\Microsoft\\WindowsApps"
        - "e:\\Users\\30840\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin"
        - "F:\\Program Files\\Microsoft VS Code\\bin"
        - "C:\\Users\\30840\\.dotnet\\tools"
        - "F:\\Program Files\\IntelliJ IDEA 2025.3.3\\bin"
        - "F:\\Program Files (x86)\\cursor\\resources\\app\\bin"
        - "F:\\Program Files (x86)\\DataGrip 2025.3.5\\bin"
        - "C:\\Users\\30840\\.dotnet\\tools"
        - "C:\\Users\\30840\\AppData\\Roaming\\npm"
        - "C:\\Users\\30840\\AppData\\Local\\Programs\\DockerDesktop\\resources\\bin"
        - "F:\\vs\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin"
        - "F:\\vs\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\Ninja"
        - "F:\\vs\\Common7\\IDE\\VC\\Linux\\bin\\ConnectionManagerExe"
        - "F:\\vs\\VC\\vcpkg"
...
